### ISSUE TITLE
error on apply plugin

### ISSUE THREAD

**Issue by xellDart** [MichaelRocks/DataBindingCompat#1]
i have this error
Error:Could not initialize class io.michaelrocks.databindingcompat.PluginVersion

**Comment by MichaelRocks** [comment]
Could you run your build with `--stacktrace` and add the stacktrace to the issue?

**Comment by MichaelRocks** [comment]
@xperiafan13-rom Any updates?

**Comment by xellDart** [comment]
Im sorry, i have this msg:
Error:Unable to find method 'kotlin.text.StringsKt.toIntOrNull(Ljava/lang/String;)Ljava/lang/Integer;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

If i re-downlaod dependencies i have:
Error:Could not initialize class io.michaelrocks.databindingcompat.PluginVersion

Now im alppy the flag on compiler... but same msg

**Comment by MichaelRocks** [comment]
@xperiafan13-rom I cannot understand why this problems occurs without logs. Can you run the following script
```
./gradlew assemble --console plain --debug --stacktrace > build.log 2>&1 
```
and attach `build.log` to this issue?

**Comment by MichaelRocks** [comment]
@xperiafan13-rom And what version of Android Gradle plugin are you using?

**Comment by MichaelRocks** [comment]
@xperiafan13-rom Seems you're using a very old version of Android Gradle plugin. I tried and fix my plugin, so I hope it'll work fine now.

**Comment by modislaszlox2** [comment]
Hello @MichaelRocks, I'm having the same issue when I try to sync the project after adding the library. Attached logs:

[filtered.log](https://github.com/MichaelRocks/DataBindingCompat/files/1406573/filtered.log)

**Comment by MichaelRocks** [comment]
@modislaszlox2 What's the version of Android Gradle plugin you're using?

**Comment by modislaszlox2** [comment]
@MichaelRocks 2.3.3

**Comment by MichaelRocks** [comment]
@modislaszlox2 Thank you. Seems the reason of this issue isn't what I expected. But it's very difficult for me to fix this bug with the information I have. It would be nice if you could build your project with `--stacktrace` flag and send me a full stacktrace. And it would be even better if you show me your `.gradle` files.

**Comment by modislaszlox2** [comment]
@MichaelRocks Issue can be reproduced easily with an empty project.
[build.log](https://github.com/MichaelRocks/DataBindingCompat/files/1414992/build.log)
[build.zip](https://github.com/MichaelRocks/DataBindingCompat/files/1415001/build.zip)
[app-build.zip](https://github.com/MichaelRocks/DataBindingCompat/files/1415007/app-build.zip)

**Comment by MichaelRocks** [comment]
@modislaszlox2 Yep, I managed to reproduce it with your `.gradle` files. Unfortunately, I don't quite understand what happens there. Seems Kotlin 1.0.x instead of 1.1.x is used at runtime for some reason. I'll try to fix it but everything should work fine with the new Android Gradle plugin 3.0.0.

**Comment by modislaszlox2** [comment]
@MichaelRocks After updating to Android Studio 3.0 and 3.0.0 gradle plugin the library works correctly. Because the gradle plugin 3.0.0 is officially released from my perspective the issue can be closed.
